# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='Tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_Due',
            field=models.DateField(default=datetime.datetime(2016, 5, 21, 11, 19, 1, 288802, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_desc',
            field=models.CharField(default=datetime.datetime(2016, 5, 21, 11, 19, 27, 423191, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_status',
            field=models.CharField(default=datetime.datetime(2016, 5, 21, 11, 19, 40, 966142, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskDetails',
        ),
    ]
